V1.0
lhr-solar/USBCPowerPCB pull request #1
Opened 2024-08-14 05:14 UTC by IshDeshpa

V1 includes:
- USB Type-C input
- 12V and 5V outputs from up to 100W USB Type-C Power Delivery Standard
- 12V bus current display

2024-08-17 06:04 UTC, Lakshay983 commented
A few things I noticed (this is not full review):
- If I fail to negotiate 12-20V and safe_pwr is used I'd like for safe_pwr to power 5V out (900 mA is enough to do most of our things)
- Add indicator LEDs to indicate you negotiated 12V or 5V. Technically power good works, but that's weird
- Personally, it makes more intuitive sense for the power flow to go vbus-> 12V converter -> 5V converter instead of them being parallel branches just because vbus is in this weird unknown state.
- Instead, you could go vbus -> 12V converter -> 5V converter -> converter output [or'd](https://www.ti.com/power-management/power-switches/ideal-diodes-oring-controllers/overview.html) with the safe_pwr to always output a stable 5V regardless of the state of vbus
- Fun fact, there's a problem with the BJT on the LDO 😢 https://github.com/lhr-solar/BPS-PeripheralSOMPCB/issues/11
- GND testpoints pls
- CC line protection? (and other output protections) https://www.ti.com/lit/an/slvaf82b/slvaf82b.pdf?ts=1723847436491
- The current power protection with nmos' is weird, could just be diode that clamps if vout is not at proper voltage

2024-08-17 06:27 UTC, Lakshay983 commented
Double check if some of these random resistor values are available on Mouser. Some of them r very specific. I also think for stuff like this it's helpful to put 0 ohm resistors in series in case u want to tune em later down the line.

For current limiting resistors on the 7-segment display should be (3.3-2.05)/.020 so I think you messed up a decimal place for those.

2024-09-02 00:08 UTC, FrankLiTX commented
Looks pretty good to me.

A couple notes:
![image](https://github.com/user-attachments/assets/b0a3bb33-a1de-49d6-bcca-b45121955484)
I double checked the resistor values and they r good but whats the reasoning behind the parallel resistors (6.2M and 240K)?

Not a big deal but maybe double check the circuitry for the output MOSFETs for the Power Delivery Controller. I saw some additional caps on the data sheet.

2024-09-02 03:53 UTC, IshDeshpa commented
The parallel resistors were just to make the values R1=55479.45205 and R2=4987.684729, but honestly I can just round up/down and call it a day since the UVLO voltage values are kinda arbitrary.

2024-09-02 21:52 UTC, Lakshay983 commented
Make sure to set your board constraints: https://github.com/lhr-solar/UTSVT-KiCadLibraries?tab=readme-ov-file#standard-constraints-for-laying-out-board

For the output connectors can you make them Molex connectors, most people have jumper wires at home compared to banana plugs and it'll be convenient to make a cable crimped with both sides of the mating connector for easy use with another board

No resistor values on R1 and R2 🤔 

Thoughts on 1x1 pin headers for testpoint footprints? Means you can easily insert wires into them for testing

<img width="889" alt="Screenshot 2024-09-02 at 4 50 52 PM" src="https://github.com/user-attachments/assets/c1285eb3-d7cd-4cc7-bba8-487239cc1acc">

Whoopsie poopsie, Looks like you connected the or out to GND for U3.

2024-09-02 22:41 UTC, Lakshay983 commented
Why use two parallel diodes? Thoughts on a priority mux? Smth like this: https://www.ti.com/product/TPS2116 (it also has a higher current limit 🫨 )

This is more preference than anything, why not use power flags instead of the net labels? 

Tbh i don't think you need these load switches. I'd rather have protection on the outputs rather than enabling mosfets based on internal Ic protection. 

Why are you doubling up on diode protection for vbus_in?

Can you standardize pulldown and pullup value (for BOM consolidation)

For the 12V -> 5V converter, the datasheet recommends 4.7uH for 5V conversions. Also, what's the vout label for on that converter.

2024-09-04 21:23 UTC, ppatra126 commented
For the 20V->12V, separate AGND and power ground on the schematic and make sure you only connect the nets at one point on the board.

![image](https://github.com/user-attachments/assets/5c40520e-f9ad-48eb-b941-f258e90191d7)
Not sure if this scheme will work. Per Lakshay Gupta, fets might just be unnecessary in general. Probably better to just protect the 12v output

![image](https://github.com/user-attachments/assets/84c0c32e-d5a1-4d62-ae61-c8fb4bc4e5f9)

2024-09-08 07:35 UTC, dimembermatt commented
Haven't gone into the nuts and bolts of the confluence design document page, but it looks like you put in a lot of thought in the design and parts selection. Will leave the deep dive for a later time when i have 6+ hours on my hands.

I guess low hanging fruit here would be BOM consolidation; how many of these passives (resistors, capacitors, inductors, fets) can be set to standard values and merged together? I also didn't see any tolerances or VDS requirements or current surge requirements in the BOM. 
![image](https://github.com/user-attachments/assets/f1782ad9-7658-4676-b661-0d62e4449bb9)

Likewise, I would suggest picking preferred suppliers for passives with a secondary supplier. Vishay seems to be my choice for resistors, Bourns for inductors, and TDK for capacitors. 

For the 12V buck and potentially others, I see that you tie these grounds together; what I've been doing on my designs lately is using the built-in net-tie symbol and footprint to tie them together to make it explicit connection at one point instead of muting the ERC.
![image](https://github.com/user-attachments/assets/597482d1-8d2e-42a2-a814-7ae950eba032)

For the 12V buck in particular, some thoughts:
- it may be preferable to design this as a semi-independent block, with test banana jack connectors on the input and output to verify against a power supply.
- it may be preferable to change the design requirements to accept an input range of 12V - 20V to accept the 12V, 15V, and 20V USB PD1.0/2.0/3.0 profiles.
- additionally, accepting 12-20V may allow you to add a barrel jack connector for some older laptop power bricks with [12V - 20V (19.5V nom)](https://electronics.stackexchange.com/questions/31618/why-do-many-laptops-run-on-19-volts) output. Is this an acceptable use case? It may be unlikely in this day and age to find laptops with older barrel jacks rather than USB C for power. If you're out on the road (ASC) and there is no AC outlet available, you might need to bootstrap from another car's 12V cigarette lighter for debugging LV boards. Although these days you can find USB C laptop chargers car adapters on Amazon for cheap.
- I didn't see any current requirement anywhere besides the design rated current; and do not know how much Lakshay needs for driving contactors; here is a simple 12V-20V high efficiency buck boost [design](https://webench.ti.com/appinfo/webench/scripts/SDP.cgi?ID=AB3DEC54DF993D94) from webench for 5A (chip supports 8A) that would enable USB PD 1.0 12V input.

2024-09-11 17:30 UTC, IshDeshpa commented
Annoying that you have to program the buck with I2C

2024-09-14 17:19 UTC, IshDeshpa commented
Ready for another schematic review @Lakshay983 @ppatra126 @FrankLiTX

2024-09-14 21:59 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/ba40fbc2-a319-4be7-b22a-f791d8173160)
nitpick but don't use more net names then you need to. Replace instances of VBUS_IN with the hierarchical net name. 

![image](https://github.com/user-attachments/assets/3716eb3a-f3ad-4c98-a60e-1a914cf27960)
The auto retry on this chip works by dumping all the charge in the capacitor when there's a fault. 22uF is a pretty big capacitance to all of a sudden short to ground. It's safer to use a 1M ohm resistor and a 2.2uF cap to set the retry time

2024-09-14 22:06 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/9e4a712a-3d19-41db-8ce7-28e4b1855cc2)
If we haven't already ordered a bunch of 3.3uH inductors, we should change the inductor value to 4.7uH as recommended by the datasheet for 12v to 5v, and also increase the capacitance on the output for a cleaner output

2024-09-14 22:27 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/6dd660ee-156d-4eb8-b5fe-a8bd8eb2d6b9)
R27, R28 are flipped
When R28 = 12k and R27 = 113K, this will set the voltage limit to 12.5 and not 12.6
Consider increasing the voltage limit to closer to 13 instead of 12.5, if for some reason we have a really crappy ripple from the buck, we don't want to accidentally trip this too soon

2024-09-14 22:34 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/e7904be1-a2d1-49cd-a81e-5c01e03e2b2e)
Consider changing the two PMOSs in here to use the same two in one PMOS package that the PD circuit uses. This will help save on the number of parts we have to order and keep track of. 
The 9.2A limit of the IRF9358TRPBF that PD uses should be plenty enough. I don't think any of our boards should be drawing anything close to that

2024-09-15 22:14 UTC, Lakshay983 commented
The isolated output protection for 5V doesn't need to be a separate chip, could just be a rresettable PTC fuse. 

Vout protection chip is hella overkill considering a lot of it is done for the input by ur buck. You really only need a diode.

Some LED comments:
- 12V power good LED could just be the power good signal providing power
- You don't need nmos on power LED

2024-09-16 03:20 UTC, IshDeshpa commented
Thinking about adding mosfet for 12V buck output for inrush current protection; diode has too high voltage drop. Not sure whether to use Power Good or separate mosfet driver.

2024-09-16 17:37 UTC, IshDeshpa commented
@Champers5000 @Lakshay983 all your comments have been addressed

2024-09-16 18:15 UTC, Lakshay983 commented
Can you make the 5V iso out connector a 4 pin connector, just so we can use a CAN cable for canbus power delivery testing.

2024-09-16 18:16 UTC, Lakshay983 commented
Thoughts on moving ur 12V output prot to vbus? Just for the reverse current protection

2024-09-16 18:18 UTC, Lakshay983 commented
@ppatra126 do you know fet you're using for LeaderSOM pp chip. Can this fet be used, or can this board use this fet.

2024-09-16 18:19 UTC, Lakshay983 commented
Can you find a PTC with a lower hold current? Nominally we'll prob have less 160mA on the line since one Can chip draws less than that.

2024-09-16 18:41 UTC, Lakshay983 commented
the banana jack symbol + footprint combo is messed up
![image](https://github.com/user-attachments/assets/a6597370-bfbc-4032-80cf-01b03cef7fab)
![image](https://github.com/user-attachments/assets/5359af8b-1b59-486b-88da-faff774010cc)

2024-09-16 18:42 UTC, Lakshay983 commented
Make testpoints pin headers or the THT testpoints so you can oscilloscope probes to em

2024-09-16 18:42 UTC, Lakshay983 requested changes
Add power over ethernet?

2024-09-16 19:05 UTC, Lakshay983 commented
> Can you find a PTC with a lower hold current? Nominally we'll prob have less 160mA on the line since one Can chip draws less than that.

Disregard this commen

2024-09-16 19:23 UTC, IshDeshpa commented
> Thoughts on moving ur 12V output prot to vbus? Just for the reverse current protection
i smell like poop
@Lakshay983 

eh probably fine
also ew why would you say that

2024-09-16 19:43 UTC, IshDeshpa commented
> Can you make the 5V iso out connector a 4 pin connector, just so we can use a CAN cable for canbus power delivery testing.

sure but what would go on the other two pins? just no connect?

2024-09-16 21:10 UTC, Lakshay983 commented
> > Can you make the 5V iso out connector a 4 pin connector, just so we can use a CAN cable for canbus power delivery testing.
> 
> sure but what would go on the other two pins? just no connect?

yeah, make it 2 no connect

2024-10-01 03:54 UTC, Lakshay983 requested changes, later dismissed
Here's some stuff after a quick glance, I need to do a more in depth dive later on.

For ur molex connectors (the top ones), add more space between the clip and the other components (mostly the pin headers and the testpoint). If you put a mating connector in there it'll be hella hard to get ur fingies in there. Also, for 4 pin connectors, make it go 5V then GNDPWR (that's the pinout we follow on other boards).

Your 5V pours are way bigger than you probably need, consider moving ur 5V isolator up closer to the mounting hole and the 5V connector where the 5V isolator used to be. There's a few ways you can also reduce the size of the 12V plane to make the overall board smaller like moving the banana jacks lower and then moving the 12V connector the side.

What's with double vias with some of the GND nets? You can get rid of most of those if you have the top also be a GND pour.

Can you make the entire top layer a GND with a low priority so anything not taken up by one of your planes is GND.

A lot of your groups are messed up (holes and testpoints on same layer, some things not in the group, etc).

Make sure to run Tools -> Cleanup Tracks and Vias. Looks there's a few stray traces on there.

SW node should be a pour. 
![image](https://github.com/user-attachments/assets/92199f0e-8cf3-45c7-b7b1-d9fae90fd3fc)

Move FB testpoint to be closer to the other FB resistors.

Overall, great job on layout, it's very clean.

2024-10-02 05:09 UTC, IshDeshpa commented
For the SW node being a pour, the datasheet explicitly said that there should be a separate trace to the upper FB resistor.
![image](https://github.com/user-attachments/assets/4c6afb91-852b-4d49-81eb-513dcaae6c61)

2024-10-04 22:05 UTC, Lakshay983 commented
The troll is really scary :( 
pls remove

2024-10-05 16:58 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/c524b12c-63c2-4f5d-a00e-54a884173874)
![image](https://github.com/user-attachments/assets/0aa043f7-2ad8-482a-bf3b-0fb783692390)


Flip these resistors to have 3V and GND facing towards the middle. This will reduce the space needed for specialized planes (3.3V), also do we really need the testpoints here? It's not hard to probe straight off of the resistor

2024-10-05 18:08 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/989cfcc1-8ca6-4838-a97f-e68f9ed48116)
Just a thought, but maybe set the Vstop voltage a bit lower? If a power supply can deliver 12V, this board should still fully work because this buck converter could act as a pass through

2024-10-05 18:15 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/4c6d0c3d-8f51-47ba-93c5-16fc4efdda19)
Also optional,
Replace the net tie with a 0 ohm resistor so if we do want to do filtering in the future, it's possible to

2024-10-05 18:17 UTC, Champers5000 commented
A buck converter with high current like this one should have more vias connecting it gnd
![image](https://github.com/user-attachments/assets/fcc65b17-ddbc-489b-a770-57e90c58e38d)

2024-10-05 18:21 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/663f770b-e316-4a11-bf87-dcda660fb5d6)

This won't work if it's connected to 12V output of buck converter. Connect this to vbus in

Also rename to power bad because LED on = there's a problem

2024-10-05 18:26 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/713336fe-ca27-4f5b-8c4f-842bc11739ae)
୧༼ಠ益ಠ༽୨

2024-10-05 18:39 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/b3fd7255-32b9-48b9-ae51-4e77a43e35a1)
Why 4 pin here?

2024-10-05 18:45 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/7de5575c-bbae-49a9-9c92-be872979987a)

12V LED will not like it's resistor value

2024-10-05 18:47 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/288edf74-f401-4a03-9f16-fa8d81a3ba7a)

Move the isolated 5v5v closer to the 5v buck output. That will eliminate the weird elongated shape of the unisolated 5v plane

2024-10-05 18:56 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/3d6db269-5882-4c4e-a687-ff24e0bb6f9c)
I think you can put the vias in pad with no extra cost as long as you don't tent your vias. I don't know what lakshay was yapping about this costing extra

2024-10-05 19:38 UTC, IshDeshpa commented
> ![image](https://private-user-images.githubusercontent.com/95988334/373898164-b3fd7255-32b9-48b9-ae51-4e77a43e35a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM4NzQsIm5iZiI6MTcyODE1MzU3NCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTgxNjQtYjNmZDcyNTUtMzJiOS00OGI5LWFlNTEtNGU3N2E0M2UzNWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjM3Mzc5YWUzYjU1OTY5OWZkZjM0YzdiN2M3NWYxYTNhMjg5NmQ3MDk1OWMyYjBiZDhhNDQ2MjQwODc0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rl-NHeZfaqUB4Ovcc2kAM_rZMM7227F456IGcIiGNTM) 
Why 4 pin here?

because lakshay wants to be able to connect our first CAN connector to it

2024-10-05 19:39 UTC, IshDeshpa commented
> ![image](https://private-user-images.githubusercontent.com/95988334/373897474-713336fe-ca27-4f5b-8c4f-842bc11739ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM2NjAsIm5iZiI6MTcyODE1MzM2MCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTc0NzQtNzEzMzM2ZmUtY2EyNy00ZjViLThjNGYtODQyYmMxMTczOWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTUxZmY1YWRiMDFjMWU3Y2FlZjBlZmFiZWNlM2I0ZWJlYWZhYzEzNWFlYTdhYjM5OTRlYjUyMDMwNDM4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IbHNTcb0JnXAveb7L2cIayrI6X0KpI8TGAnli839hNg) ୧༼ಠ益ಠ༽୨

The datasheet did this so i did it

2024-10-05 19:49 UTC, IshDeshpa commented
> ![image](https://private-user-images.githubusercontent.com/95988334/373896025-989cfcc1-8ca6-4838-a97f-e68f9ed48116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM2NjAsIm5iZiI6MTcyODE1MzM2MCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTYwMjUtOTg5Y2ZjYzEtOGNhNi00ODM4LWE5N2YtZTY4ZjllZDQ4MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NWJkYTcxY2Q0Mjk5YTRiNThjOWZlYWE4YzZlOTQyNjFmN2M5OTYyZTJmYWRkOWZmYzIxZWVlMmY2ODM1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bTL6AnwVMNxpL1Lsv_Kxt2JGYJ_7UgcRyFQLn1sI5JM) Just a thought, but maybe set the Vstop voltage a bit lower? If a power supply can deliver 12V, this board should still fully work because this buck converter could act as a pass through

At least rn this board is only designed for 15/20V chargers bc: 
- 12 into a 12v buck is bad
- most laptop chargers are 15/20v and not 12v, iirc 12v is an optional standard now on USBC pd

2024-10-05 20:58 UTC, IshDeshpa commented
> ![image](https://private-user-images.githubusercontent.com/95988334/373897154-663f770b-e316-4a11-bf87-dcda660fb5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM2NjAsIm5iZiI6MTcyODE1MzM2MCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTcxNTQtNjYzZjc3MGItZTMxNi00YTExLWJmODctZGNkYTY2MGZiNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4Y2E1MjJlMmUzZDM3YWNjYmQ5YjkzZTQxYmFkYzZlMTUyZWJjZjA1NzU5N2IyYTVkMDZkMDExMGM2ZmY2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j62E6zzR_2pyy34Gw6VIquDagQ8Ul34Gbb4udqPAlXA)
> 
> This won't work if it's connected to 12V output of buck converter. Connect this to vbus in
> 
> Also rename to power bad because LED on = there's a problem

This is for the 12V output of the buck converter, not for general VBUS. Also, since POWER_GOOD is pulled to Hi-Z when the power is good, the LED will turn on when the power is good, otherwise the POWER_GOOD pin should just sink the current and not turn on the LED.

2024-10-06 21:32 UTC, Champers5000 commented
> > ![image](https://private-user-images.githubusercontent.com/95988334/373897154-663f770b-e316-4a11-bf87-dcda660fb5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM2NjAsIm5iZiI6MTcyODE1MzM2MCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTcxNTQtNjYzZjc3MGItZTMxNi00YTExLWJmODctZGNkYTY2MGZiNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4Y2E1MjJlMmUzZDM3YWNjYmQ5YjkzZTQxYmFkYzZlMTUyZWJjZjA1NzU5N2IyYTVkMDZkMDExMGM2ZmY2OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j62E6zzR_2pyy34Gw6VIquDagQ8Ul34Gbb4udqPAlXA)
> > This won't work if it's connected to 12V output of buck converter. Connect this to vbus in
> > Also rename to power bad because LED on = there's a problem
> 
> This is for the 12V output of the buck converter, not for general VBUS. Also, since POWER_GOOD is pulled to Hi-Z when the power is good, the LED will turn on when the power is good, otherwise the POWER_GOOD pin should just sink the current and not turn on the LED.

Ok my bad, I see the vision now. Schematic is fine

2024-10-06 21:33 UTC, Champers5000 commented
> > ![image](https://private-user-images.githubusercontent.com/95988334/373896025-989cfcc1-8ca6-4838-a97f-e68f9ed48116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM2NjAsIm5iZiI6MTcyODE1MzM2MCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTYwMjUtOTg5Y2ZjYzEtOGNhNi00ODM4LWE5N2YtZTY4ZjllZDQ4MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NWJkYTcxY2Q0Mjk5YTRiNThjOWZlYWE4YzZlOTQyNjFmN2M5OTYyZTJmYWRkOWZmYzIxZWVlMmY2ODM1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bTL6AnwVMNxpL1Lsv_Kxt2JGYJ_7UgcRyFQLn1sI5JM) Just a thought, but maybe set the Vstop voltage a bit lower? If a power supply can deliver 12V, this board should still fully work because this buck converter could act as a pass through
> 
> At least rn this board is only designed for 15/20V chargers bc:
> 
>     * 12 into a 12v buck is bad
> 
>     * most laptop chargers are 15/20v and not 12v, iirc 12v is an optional standard now on USBC pd

Makes sense, this is also something we could change later on by swapping resistors anyways so it's not too important

2024-10-06 21:35 UTC, Champers5000 commented
> > ![image](https://private-user-images.githubusercontent.com/95988334/373897474-713336fe-ca27-4f5b-8c4f-842bc11739ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNTM2NjAsIm5iZiI6MTcyODE1MzM2MCwicGF0aCI6Ii85NTk4ODMzNC8zNzM4OTc0NzQtNzEzMzM2ZmUtY2EyNy00ZjViLThjNGYtODQyYmMxMTczOWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE4MzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTUxZmY1YWRiMDFjMWU3Y2FlZjBlZmFiZWNlM2I0ZWJlYWZhYzEzNWFlYTdhYjM5OTRlYjUyMDMwNDM4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IbHNTcb0JnXAveb7L2cIayrI6X0KpI8TGAnli839hNg) ୧༼ಠ益ಠ༽୨
> 
> The datasheet did this so i did it

Datasheet layout is trash, just ignore it. There's no reason to make the 5V output extra long and more susceptible to interference.

2024-10-06 21:40 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/4989b133-b091-4d5e-828f-d697528d9990)
This chip pinout kinda infuriates me. TI did not do a good job with choosing which pins should be which in this package. Very suboptimal

2024-10-09 21:16 UTC, IshDeshpa commented
Do I need ESD protection on the output or some sort of polarity reversal or should i just assume the board has that? i don't wanna destroy my output shit

2024-10-12 14:48 UTC, sodaplayzz commented
Schematic looks good, most of it is from datasheets, which are followed correctly.

2024-10-13 05:36 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/01426cb5-2e99-45c5-ba0d-216ebd075191)
Why is R7 on the back and not the front like the other resisotrs

2024-10-13 05:38 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/6af4784c-22ad-4218-9a47-7d1079d3a7f6)
Love the naming of the nets

2024-10-13 05:47 UTC, Champers5000 commented
![image](https://github.com/user-attachments/assets/6e3f348f-d6a2-4afb-9c86-bbf14b964202)
What is this silkscreen referring to

2024-10-13 05:48 UTC, Champers5000 commented
> Do I need ESD protection on the output or some sort of polarity reversal or should i just assume the board has that? i don't wanna destroy my output shit

Also yes this would be a good idea. We would need not necessarily ESD protection, but rather transient voltage protection in the case something fails short. Search for TVS diodes

2024-10-13 05:57 UTC, Champers5000 commented
silkscreen on the back like this is so cursed. I'm gonna push a commit that ends this

2024-10-13 21:00 UTC, IshDeshpa commented
> > Do I need ESD protection on the output or some sort of polarity reversal or should i just assume the board has that? i don't wanna destroy my output shit
> 
> Also yes this would be a good idea. We would need not necessarily ESD protection, but rather transient voltage protection in the case something fails short. Search for TVS diodes

I have TVS diodes on the input so could I just grab those and stick em on the outputs too

2024-10-17 17:16 UTC, connorl309 commented
What's up with the component values on the pd controller? Some of them don't follow datasheet app. Same for some of the converters.

2024-10-17 17:21 UTC, connorl309 commented
![image](https://github.com/user-attachments/assets/977fef81-b8c6-4e2d-9613-8a554dc27b17)

These power plane connections seem sketchy. What's the input current on VIN for the 12V converter? Why not use solid connections instead of thermal reliefs (you already have two copper pours that will suck away a bunch of the heat)

2025-02-04 22:36 UTC, merged